<?php
// Sección de título
$lang['bee2citizen_page_title1_h1'] = 'bee2citizen';
$lang['bee2citizen_page_title1_img1'] = 'section-title-background.jpg';
$lang['bee2citizen_page_title1_img2'] = 'section-title-logo.png';
$lang['bee2citizen_page_title1_span1'] = 'All in one app. All for the citizen.';
$lang['bee2citizen_page_title1_span2'] = ' The Municipality in your pocket';
$lang['bee2citizen_page_title1_li1'] = 'Home';
$lang['bee2citizen_page_title1_li2'] = 'Products';
$lang['bee2citizen_page_title1_li3'] = 'bee2citizen';

// Sección 1
$lang['bee2citizen_heading_block0_h1'] = 'The New Form Of Citizenship';
$lang['bee2citizen_heading_block0_img1'] = 'bee2citizen-section1-img1.png';
$lang['bee2citizen_heading_block0_p1'] = 'Proactiveness powering the link between the Citizens and Municipality.';
$lang['bee2citizen_heading_block0_p2'] = 'The participation and information generated by active citizens will help Boards/Chambers make better decisions for their community.';
$lang['bee2citizen_heading_block0_p3'] = 'With only one single channel for interaction, this app is easy to use and is always at the palm of your hand.';

// Sección 2
$lang['bee2citizen_heading_block1_h1'] = 'Streamlining the Link between Citizens and Municipality';
$lang['bee2citizen_heading_block1_img1'] = 'bee2citizen-section2-img1.jpg';
$lang['bee2citizen_heading_block1_p1'] = 'With the digital age, Citizenship has evolved into Cyber ​​Citizenship, which makes citizens the main actors in their community. Social networks, mobility and constant web connection are factors that cannot be overlooked. The participation and information generated by the active participation of the citizens have particular importance for the Boards/ Chambers in order to be able to structure better decision making.';

// Sección 3
$lang['bee2citizen_heading_block2_h1_1'] = 'Limitless';
$lang['bee2citizen_heading_block2_h1_2'] = 'Share';
$lang['bee2citizen_heading_block2_h1_3'] = 'Speed';
$lang['bee2citizen_heading_block2_h1_4'] = 'Push';
$lang['bee2citizen_heading_block2_p1'] = 'Since it isn’t only limited to your municipality, you can add as many cities as you wish. Updated information for local boards is a powerful channel powering the next step in governance.';
$lang['bee2citizen_heading_block2_p2'] = 'You can explore informations in detail and directly share from your smartphone through the main social networks or wherever you want. Sharing is the new power!';
$lang['bee2citizen_heading_block2_p3'] = 'Availability of various services, which accelerates the entire process of interaction with your Municipality. You can request a local service from your smartphone.';
$lang['bee2citizen_heading_block2_p4'] = 'It will always notify with push functionality. Whenever there is any relevant information update by the municipality, you will be prompted with a push message.';
$lang['bee2citizen_heading_block2_img1'] = 'bee2citizen-section3-img1.jpg';
$lang['bee2citizen_heading_block2_img2'] = 'bee2citizen-section3-img2.jpg';
$lang['bee2citizen_heading_block2_img3'] = 'bee2citizen-section3-img3.jpg';
$lang['bee2citizen_heading_block2_img4'] = 'bee2citizen-section3-img4.jpg';

// Sección 4
$lang['bee2citizen_heading_block3_h1'] = 'Main features';
$lang['bee2citizen_heading_block3_img1'] = 'bee2citizen-section4-img1.jpg';
$lang['bee2citizen_heading_block3_img1'] = 'bee2citizen-section4-img1.jpg';
$lang['bee2citizen_heading_block3_img1'] = 'bee2citizen-section4-img1.jpg';
$lang['bee2citizen_heading_block3_title1'] = 'Referendum';
$lang['bee2citizen_heading_block3_title2'] = 'Budgeting';
$lang['bee2citizen_heading_block3_title3'] = 'News';
$lang['bee2citizen_heading_block3_title4'] = 'Useful contacts';
$lang['bee2citizen_heading_block3_title5'] = 'Oversized Waste Collection';
$lang['bee2citizen_heading_block3_title6'] = 'Pets registration';
$lang['bee2citizen_heading_block3_title7'] = 'Events';
$lang['bee2citizen_heading_block3_title8'] = 'Issue reporting';
$lang['bee2citizen_heading_block3_p1'] = 'Your opinion matters.';
$lang['bee2citizen_heading_block3_p2'] = 'Have an active role in your city. Suggest, vote and partake.';
$lang['bee2citizen_heading_block3_p3'] = 'Be the first to know what is happening in your area. The news will always be reliable since they are published by the parish itself.';
$lang['bee2citizen_heading_block3_p4'] = 'Hospitals, Firefighters, Police and the contacts that you may need in case of emergency at the palm of your hands.';
$lang['bee2citizen_heading_block3_p5'] = 'Schedule the collection of abnormal waste (sofas, fridges, similar) with your city.';
$lang['bee2citizen_heading_block3_p6'] = 'In a few clicks, register your pet in a remotely and innovative way.';
$lang['bee2citizen_heading_block3_p7'] = 'It’s weekend and you don’t have any plans? With this app you can find events happening near you.';
$lang['bee2citizen_heading_block3_p8'] = 'Find out and avoid all issues that may harm your day.';

// Sección 5
$lang['bee2citizen_heading_block4_h1'] = 'Unique Backoffice Management Tool';
$lang['bee2citizen_heading_block4_img1'] = 'bee2citizen-section5-img1.png';
$lang['bee2citizen_heading_block4_img2'] = 'bee2citizen-section5-img2.jpg';
$lang['bee2citizen_heading_block4_img3'] = 'bee2citizen-section5-img3.jpg';
$lang['bee2citizen_heading_block4_p1'] = 'A powerful tool for municipalities to easily manage their relationship with citizens';

// Sección 6
$lang['bee2citizen_heading_block5_h1'] = 'Impacts & Benefits';
$lang['bee2citizen_heading_block5_img1'] = 'bee2citizen-section6-img1.jpg';
